### ISSUE TITLE
请问怎么添加菜单导航？

### ISSUE THREAD

**Issue by abcdexx** [kinggozhang/hexo-theme-ace#1]
请问怎么添加菜单导航？

**Comment by kinggozhang** [comment]
```
hexo new page your_menu
```
then
```
cd source/your_menu
vi index.md
```
add 'menu: true'   
```
---

menu: true

---
```

**Comment by abcdexx** [comment]
![image](https://user-images.githubusercontent.com/28626756/59649204-6f5cbc00-91b4-11e9-8fe8-3f499a665a17.png)
添加菜单后 报错了

**Comment by kinggozhang** [comment]
先忽略这个exception, 应该不影响功能的。

**Comment by kinggozhang** [comment]
最新版本支持更便捷的添加导航菜单方法。
可以直接在_config.yml  中修改navmenu数据
