### ISSUE TITLE
请问文章内部目录为什么没有自动生成呢?

### ISSUE THREAD

**Issue by stormDL** [kinggozhang/hexo-theme-ace#12]
这个是需要配置什么吗?

**Comment by kinggozhang** [comment]
你的内部目录是指什么，你要新建目录？ 
能否具体一点？

**Comment by stormDL** [comment]
文章阅读界面右边的Contents目录,也就是文章内部标题的导航.

![2](https://user-images.githubusercontent.com/23137138/75859241-99ced200-5e34-11ea-9762-46fb7301f471.png)

**Comment by kinggozhang** [comment]
如果你的文章使用标准 Markdown 格式，
所有以#开头的段落都会生成目录才对

**Comment by stormDL** [comment]
好的,谢谢
