### ISSUE TITLE
请问怎么换header的背景图片

### ISSUE THREAD

**Issue by yuanjinzhong** [kinggozhang/hexo-theme-ace#8]
首页上面的背景图片怎么换

**Comment by kinggozhang** [comment]
layout/_partial/header.ejs， 在intro-header中增加backgrou.d-image

       header.intro-header{
       background-image: url('img/small/default.jpg')
       }

**Comment by yuanjinzhong** [comment]
谢谢，管用，点赞

**Comment by yuanjinzhong** [comment]
你好，请问这个背景图片怎么调整大小啊

**Comment by kinggozhang** [comment]
so一下  background-repeat
